### ISSUE TITLE
ValueError: Fernet key must be 32 url-safe base64-encoded bytes.

### ISSUE THREAD

**Issue by alexynior28** [Atharv-Attri/Physical2FA#1]
Hi,

The fail_safe.py file works fine for me, but the other thing doesn't. It's actually two problems. 

The first one to decrypt (USB, on D disk, NTFS formatted):

```
None
Traceback (most recent call last):
  File "lock.py", line 1, in <module>
    from Physical2FA import decrypt
  File "C:\Python38-32\lib\site-packages\Physical2FA\decrypt.py", line 47, in <module>
    decrypt(i, pubkey)
  File "C:\Python38-32\lib\site-packages\Physical2FA\decrypt.py", line 31, in decrypt
    f = Fernet(key)
  File "C:\Python38-32\lib\site-packages\cryptography\fernet.py", line 37, in __init__
    raise ValueError(
ValueError: Fernet key must be 32 url-safe base64-encoded bytes.
```

The second for encryption (USB, on D-disk, formatted in FAT32):
*With files in the root it works, but with folders ('bb') I get the following error.

```
lock.py
you will encrypt the following files: ['aa', 'bb', 'key.key', 'lock.py', 'System Volume Information', 'WhatsAppImage.png']. Are you sure you want to continue? y/n: y
['aa', 'bb', 'key.key', 'lock.py', 'System Volume Information', 'WhatsAppImage.png']
None
None
['a.png', 'b.png', 'c.png', 'd.png', 'e.png', 'f.png', 'g.png']
['a.png', 'b.png', 'c.png', 'd.png', 'e.png', 'f.png', 'g.png']
[]
Traceback (most recent call last):
  File "D:\lock.py", line 1, in <module>
    from Physical2FA import encrypt
  File "C:\Python38-32\lib\site-packages\Physical2FA\encrypt.py", line 46, in <module>
    os.chdir(i)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'bb'
```

Could you give me an idea of what I might be doing wrong? Thanks

I have performed the following steps:

- First execution:
```
from Physical2FA import write_key
write_key
```

- Second execution:
```
from Physical2FA import encrypt
encrypt
```

- Third execution:
```
from Physical2FA import decrypt
decrypt
```

**Comment by Atharv-Attri** [comment]
Thanks for bringing this up! Can you include the key that it wrote and the file structure, that will help me see what went wrong!

Thanks, and sorry for the inconvenience

**Comment by alexynior28** [comment]
I think I already deleted the structure, but I tried again and I have the same mistake

```
 Directorio de D:\

18/06/2020  23:27             1,636 fail_safe.py
18/06/2020  23:27               100 EXAMPLE.txt
18/06/2020  23:27               140 key.key
18/06/2020  23:27           844,364 WhatsAppImage.png
18/06/2020  22:52    <DIR>          ImagenesPosts
18/06/2020  22:50    <DIR>          VideoInstagram
18/06/2020  23:27                40 lock.py
```

Error:

```
D:\>lock.py
you will encrypt the following files: ['System Volume Information', 'fail_safe.py', 'EXAMPLE.txt', 'key.key', 'WhatsAppImage.png', 'ImagenesPosts', 'VideoInstagram', 'lock.py']. Are you sure you want to continue? y/n: y
['System Volume Information', 'fail_safe.py', 'EXAMPLE.txt', 'key.key', 'WhatsAppImage.png', 'ImagenesPosts', 'VideoInstagram', 'lock.py']
None
None
None
['WPSettings.dat', 'IndexerVolumeGuid']
['WPSettings.dat', 'IndexerVolumeGuid']
[]
Traceback (most recent call last):
  File "D:\lock.py", line 1, in <module>
    from Physical2FA import encrypt
  File "C:\Python38-32\lib\site-packages\Physical2FA\encrypt.py", line 46, in <module>
    os.chdir(i)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'ImagenesPosts'
```

![error](https://user-images.githubusercontent.com/19245743/85096964-8fee9600-b1bb-11ea-84b3-2479a486afea.PNG)

**Comment by alexynior28** [comment]
These are the subdirectories

\ImagenesPosts
-a.png
-b.png
-c.png
-d.png
-e.png
-f.png
-g.png

/VideoInstagram
-URLCADIZ.mp4

**Comment by Atharv-Attri** [comment]
I see the problem, you are running the program in the D drive. That also encrypts the key, causing the error, also you should not have the fail-safe in the directories that you are going to encrypt. 

Try that and see if it works!

**Comment by alexynior28** [comment]
Hi, I've tried the following:

- I've placed the files I want to encrypt in a new folder called SECRET.
- I have placed the lock.py file there
- The key.key file has been left in the root of the D drive (it is not in the SECRET folder)

I get the same result :/

![error2](https://user-images.githubusercontent.com/19245743/85097597-9bdb5780-b1bd-11ea-8616-09439cd2d61b.PNG)

**Comment by Atharv-Attri** [comment]
Sorry for not being clear, can you try it out of the D drive?

**Comment by alexynior28** [comment]
I think it's a problem with the folder. Because when I place files, it does work correctly.

Sorry, how do I run it on the D root if when I run it the key.key file will be encrypted?

**Comment by alexynior28** [comment]
I get the same as in the beginning. I'm sorry if I didn't understand you correctly :/

![error3](https://user-images.githubusercontent.com/19245743/85098033-05a83100-b1bf-11ea-8bc7-54bc089e7cd1.PNG)

**Comment by Atharv-Attri** [comment]
> I think it's a problem with the folder. Because when I place files, it does work correctly.
> 
> Sorry, how do I run it on the D root if when I run it the key.key file will be encrypted?

If the folder is empty, it will cause the error (My bad, Should've mentioned that in the README). What I mean is, try to run it somewhere on the C drive (maybe a subdirectory on your Desktop). It's made to ignore everything in the D drive, but if you run it in the D drive, it will encrypt the key.

**Comment by alexynior28** [comment]
Oh, great. Now I understand everything.

A thousand apologies! I should have understood 😂

It's working fine! Thank you very much for your assistance!

**Comment by Atharv-Attri** [comment]
It's my fault for not being clear in the README. I'll be sure to update the README in the upcoming version 1.2.0. 

Thanks for pointing this out!
